apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-dev
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/jpoplar3000/argocd-applications.git
    targetRevision: HEAD
    path: helm-charts/grafana
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
